name: genai-prep
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - click=8.3.1=pyha7b4d00_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - faiss=1.9.0=py310hbf8e942_0_cpu
  - faiss-cpu=1.9.0=hf9c7e24_0
  - ipython=8.37.0=pyha7b4d00_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - libblas=3.11.0=4_hf2e6a31_mkl
  - libcblas=3.11.0=4_h2a3cdd5_mkl
  - libexpat=2.7.3=hac47afa_0
  - libfaiss=1.9.0=h3a9ed07_0_cpu
  - libffi=3.5.2=h52bdfb6_0
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.11.0=4_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libsqlite=3.51.1=hf5d6505_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.15.1=h5d26750_0
  - libxml2-16=2.15.1=h692994f_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.7=h4fa8253_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.3.0=hac47afa_454
  - nltk=3.9.2=pyhcf101f3_1
  - numpy=1.26.4=py310hf667824_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310hed136d8_2
  - parso=0.8.5=pyhcf101f3_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyh8b19718_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.19=hc20f281_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - regex=2025.11.3=py310h29418f3_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.13=h2c6b04d_3
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - pip:
      - anyio==4.12.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - debugpy==1.8.17
      - defusedxml==0.7.1
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - fqdn==1.5.1
      - fsspec==2025.12.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - ipykernel==7.1.0
      - isoduration==20.11.0
      - jinja2==3.1.6
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - lark==1.3.1
      - markupsafe==3.0.3
      - mistune==3.1.4
      - mpmath==1.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - notebook==7.5.0
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - pillow==12.0.0
      - platformdirs==4.5.1
      - prometheus-client==0.23.1
      - psutil==7.1.3
      - pycparser==2.23
      - python-json-logger==4.0.0
      - pywinpty==3.0.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - send2trash==1.8.3
      - sentence-transformers==5.1.2
      - soupsieve==2.8
      - sympy==1.14.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.9.1
      - tornado==6.5.2
      - transformers==4.57.3
      - uri-template==1.3.0
      - urllib3==2.6.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
